events {}

http {
    upstream storytel {
        server 127.0.0.1:8000;
    }

    upstream audioteka {
        server 127.0.0.1:8001;
    }

    upstream lubimyczytac {
        server 127.0.0.1:8002;
    }

    upstream bookbeat {
        server 127.0.0.1:8003;
    }

    upstream virtualo {
        server 127.0.0.1:8004;
    }

    server {
        listen 3000;
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://storytel;
        }
    }

    server {
        listen 3001;
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://audioteka;
        }
    }

    server {
        listen 3002;
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://lubimyczytac;
        }
    }

    server {
        listen 3003;
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://bookbeat;
        }
    }

    server {
        listen 3004;
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://virtualo;
        }
    }
}
