events {}

http {
    upstream storytel {
        server 127.0.0.1:8000;
    }

    upstream audioteka {
        server 127.0.0.1:8001;
    }

    server {
        listen 3000;
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://storytel;
        }
    }

    server {
        listen 3001;
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://audioteka;
        }
    }
}
