events {}

http {
    upstream app {
        server 127.0.0.1:8000;
    }

    server {
        listen 3000;
        location / {
            proxy_set_header X-Provider storytel;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://app;
        }
    }

    server {
        listen 3001;
        location / {
            proxy_set_header X-Provider audioteka;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://app;
        }
    }
}
